### ISSUE TITLE
View count stuck on 17 

### ISSUE THREAD

**Issue by abbey-titcomb** [radicle-dev/rad-radio#16]
Not sure why, but the view count has been 17 people each time I go to the stream page. Is this a bug?

**Comment by efstajas** [comment]
The method of determining viewcount is not 100% accurate, it depends on people sending a connect and disconnect signal. The latter is sometimes missed, so the viewcount after a while is a big higher than reality. As long as we reset it every now and then it's not too much of a problem though.
